[package]
name = "photo_matcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xplr = "0.21.3"
chrono = "0.4.26"
humantime = "2.1.0"
kamadak-exif = "0.5.5"